Feature/improve read speed mk2
LLNL/PyDV pull request #269
Opened 2022-06-09 18:04 UTC by fillmore1

### Description

Resolves #267 

Update `pydvpy.read()` to improve performance

### Checklist:

- [ ] I have run the image tests on RZ and they pass.
- [ ] I have run the WSC tests on RZ and they pass.
- [ ] I have made corresponding changes to the documentation.
- [ ] I have build the docs on sphinx and they look correct.
- [ ] I have updated the release notes.
- [ ] I have run `pydv/scripts/update_version_and_date.py <major, minor, patch>`.

2022-06-13 17:01 UTC, rusu24edward requested changes
Thanks for the PR! Two things that I listed above. Unfortunately the new reader is unable to pick up some of the nuances of what defines a new curve. In some tests, it adds too many curves, in other tests it does not add enough. I can send you the test files on RZ if you want to iterate faster.

2022-06-13 17:39 UTC, fillmore1 commented on pydv/pydvpy.py
> +                elif split_line[0] == '#':  # check for start of new curve
It seems like `##` should be used for that kind of comment, but I understand keeping it for backwards compatibility. The new commits should resolve this.

2022-06-13 17:41 UTC, fillmore1 commented on pydv/pydvpy.py
> +                    curve_name = ' '.join(split_line)
I forgot to exclude the first token. My bad.
The new commits should resolve this.

2022-06-13 18:54 UTC, rusu24edward commented on pydv/pydvpy.py
> +                elif split_line[0] == '#':  # check for start of new curve
I agree, but years of users using "#" for generic comments outweighs me ;)

2022-06-13 18:59 UTC, rusu24edward requested changes
The issue with the title having "#" has been resolved. And it appears that you are not storing more curves than actually exists in the ultra file. However, the new reader still struggles to stores curves for many of the test ultra files.

2022-06-24 19:49 UTC, rusu24edward requested changes

2022-08-11 16:18 UTC, rusu24edward commented
Closing in favor of #271

2022-08-11 16:18 UTC, closed without merging